// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Webcruiter = import("./webcruiter").Webcruiter;

declare global {
  interface XpPartMap {
    "no.item.webcruiter:webcruiter": Webcruiter;
  }
}
